demotemplate/urls.py
from django.urls import include, path
from django.contrib import admin

urlpatterns = [
    path('', include('main.urls')),
    path('admin/', admin.site.urls),
]

main/urls.py
from django.urls import path

from . import views
from . import views_notebook_details
from . import views_comments

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('complete/', views.complete, name='complete'),
    path('delete-user/', views.delete_user, name='delete-user'),
    path('shared/', views.shared, name='shared'),
    path('logout/', views.logout_user, name='logout'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('notebooks/', views.notebook_index, name='notebook-index'),
    path('search/', views.search_notebooks, name='search'),
    path('likes/', views.likes, name='likes'),
    path('sources/', views.data_source_index, name='data-source-index'),
    path(
        'notebook_by_source/',
        views.notebook_by_source, name='notebook_by_source'),
    path('notebook/<notebook_id>/',
         views_notebook_details.notebook_details,
         name='notebook-details'),
    path('open-notebook/<notebook_id>/',
         views_notebook_details.open_notebook_hub,
         name='open-notebook'),
    path('add-notebook-gallery/<notebook_id>/',
         views.add_notebook,
         name='add-notebook-gallery'),
    path('edit-notebook/<notebook_id>/',
         views.edit_notebook,
         name='edit-notebook'),
    path('render-notebook/<notebook_id>/',
         views_notebook_details.render_notebook,
         name='render-notebook'),
    path('delete-notebook/<notebook_id>/',
         views.delete_notebook,
         name='delete-notebook'),
    path('export-notebook/<notebook_id>/',
         views_notebook_details.export_notebook,
         name='export-notebook'),
    path('add-comment/<notebook_id>/',
         views_comments.add_comment,
         name='add-comment'),
    path('like-notebook/<notebook_id>/',
         views_notebook_details.like_notebook,
         name='like-notebook')
]

main/models.py
from django.db import models
from open_humans.models import OpenHumansMember
from datetime import timedelta
import arrow
import json


class SharedNotebook(models.Model):
    """
    Store OAuth data for a data source.
    This is a one to one relationship with a OpenHumansMember model
    You can find the OpenHumansMember model in open_humans/models.py

    There is a bi-directional link, called oh_member from this object.
    This could be used
    to fetch the OpenHumansMember object given a DataSourceMember object.
    """
    oh_member = models.ForeignKey(OpenHumansMember, on_delete=models.CASCADE)
    notebook_name = models.TextField(default='')
    notebook_content = models.TextField(default='')
    description = models.TextField(default='')
    tags = models.TextField(default='')
    data_sources = models.TextField(default='')
    views = models.IntegerField(default=0)
    # Your other fields should go below here
    updated_at = models.DateTimeField(
                            default=(arrow.now() - timedelta(days=7)).format())
    created_at = models.DateTimeField(
                            default=(arrow.now() - timedelta(days=7)).format())
    master_notebook = models.ForeignKey('self',
                                        on_delete=models.SET_NULL,
                                        blank=True,
                                        null=True)

    def get_tags(self):
        return ",".join(json.loads(self.tags)) if self.tags else ''

    def get_data_sources(self):
        if self.data_sources:
            return ",".join(json.loads(self.data_sources))
        else:
            return ''

    def get_tags_json(self):
        return json.loads(self.tags)

    def get_data_sources_json(self):
        return json.loads(self.data_sources)


class NotebookComment(models.Model):
    """
    comments about a given notebook
    """
    oh_member = models.ForeignKey(OpenHumansMember, on_delete=models.CASCADE)
    notebook = models.ForeignKey(SharedNotebook, on_delete=models.CASCADE)
    comment_text = models.TextField(default='')
    created_at = models.DateTimeField(default=arrow.now().format())

    class Meta:
            ordering = ["created_at"]


class NotebookLike(models.Model):
    """
    like a given notebook
    """
    oh_member = models.ForeignKey(OpenHumansMember, on_delete=models.CASCADE)
    notebook = models.ForeignKey(SharedNotebook, on_delete=models.CASCADE)
    created_at = models.DateTimeField(default=arrow.now().format())

main/views.py
import logging
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login, logout
from django.shortcuts import render, redirect
from django.conf import settings
from ohapi import api
from .helpers import get_notebook_files, get_notebook_oh, download_notebook_oh
from .helpers import find_notebook_by_keywords, get_all_data_sources
from .helpers import suggest_data_sources, add_notebook_helper
from .helpers import paginate_items, oh_code_to_member
from .helpers import get_all_data_sources_numeric
from .models import SharedNotebook
import arrow
import json
from django.db.models import Count
from django.urls import reverse
from django.http import JsonResponse

# Set up logging.
logger = logging.getLogger(__name__)


def shared(request):
    """
    Users get linked here after clicking export
    on notebooks.openhumans.org
    """
    if request.user.is_authenticated:
        messages.info(request,
                      ("Your notebook was uploaded into your Open Humans "
                       "account and can now be shared from here!"))
        return redirect('/dashboard')
    latest_notebooks = SharedNotebook.objects.all(
        ).order_by('-updated_at')[:10]
    context = {'latest_notebooks': latest_notebooks}
    return render(request, 'main/shared.html', context)


def index(request):
    """
    Starting page for app.
    """
    if request.user.is_authenticated:
        return redirect('/notebooks')
    else:
        latest_notebooks = SharedNotebook.objects.filter(
            master_notebook=None).order_by('-views')[:5]
        data_sources = get_all_data_sources()[:6]
        context = {'oh_proj_page': settings.OH_ACTIVITY_PAGE,
                   'latest_notebooks': latest_notebooks,
                   'data_sources': data_sources}

        return render(request, 'main/index.html', context=context)


def data_source_index(request):
    data_sources = get_all_data_sources_numeric()
    return render(request, 'main/sources_index.html', {
                'section': 'sources',
                'data_sources': data_sources})


def about(request):
    return render(request, 'main/about.html', {'section': 'about'})


@login_required(login_url="/")
def delete_user(request):
    if request.method == "POST":
        request.user.delete()
        messages.info(request, "Your account was deleted!")
        logout(request)
    return redirect('index')


def complete(request):
    """
    Receive user from Open Humans. Store data, start upload.
    """
    # print("Received user returning from Open Humans.")
    # Exchange code for token.
    # This creates an OpenHumansMember and associated user account.
    code = request.GET.get('code', '')
    oh_member = oh_code_to_member(code=code)

    if oh_member:
        # Log in the user.
        user = oh_member.user
        login(request, user,
              backend='django.contrib.auth.backends.ModelBackend')
        return redirect("/dashboard")

    logger.debug('Invalid code exchange. User returned to starting page.')
    return redirect('/')


@login_required(login_url="/")
def logout_user(request):
    """
    Logout user
    """
    if request.method == 'POST':
        logout(request)
    return redirect('index')


@login_required(login_url='/')
def dashboard(request):
    oh_member = request.user.oh_member
    context = {
        'oh_member': oh_member,
    }
    try:
        oh_member_data = api.exchange_oauth2_member(
                            oh_member.get_access_token())
    except:
        messages.error(request, "You need to re-authenticate with Open Humans")
        logout(request)
        return redirect("/")
    all_available_notebooks = get_notebook_files(oh_member_data)
    existing_notebooks = SharedNotebook.objects.filter(oh_member=oh_member)
    context = {
        'notebook_files': all_available_notebooks,
        'existing_notebooks': existing_notebooks,
        'JH_URL': settings.JUPYTERHUB_BASE_URL,
        'base_url': request.build_absolute_uri("/").rstrip('/'),
        'section': 'dashboard'}
    return render(request, 'main/dashboard.html',
                  context=context)


@login_required(login_url='/')
def likes(request):
    oh_member = request.user.oh_member
    liked_notebook_list = oh_member.notebooklike_set.all().order_by('-created_at')
    liked_notebooks = paginate_items(
                        liked_notebook_list,
                        request.GET.get('page'))
    return render(request, 'main/likes.html',
                  context={'liked_notebooks': liked_notebooks,
                           'section': 'likes'})


@login_required(login_url='/')
def add_notebook(request, notebook_id):
    oh_member = request.user.oh_member
    try:
        oh_member_data = api.exchange_oauth2_member(
                                oh_member.get_access_token())
    except:
        messages.error(request, "You need to re-authenticate with Open Humans")
        logout(request)
        return redirect("/")

    notebook_name, notebook_url = get_notebook_oh(oh_member_data, notebook_id)

    if request.method == 'POST':
        add_notebook_helper(request, notebook_url, notebook_name, oh_member)
        return redirect('/dashboard')
    else:
        if len(SharedNotebook.objects.filter(oh_member=oh_member,
                                             notebook_name=notebook_name)) > 0:
            existing_notebook = SharedNotebook.objects.get(
                                        oh_member=oh_member,
                                        notebook_name=notebook_name)
            context = {'description': existing_notebook.description,
                       'tags': existing_notebook.get_tags(),
                       'data_sources': existing_notebook.get_data_sources(),
                       'name': notebook_name,
                       'notebook_id': str(notebook_id),
                       'edit': True}
        else:
            notebook_content = download_notebook_oh(notebook_url)
            suggested_sources = suggest_data_sources(notebook_content)
            context = {'description': '',
                       'name': notebook_name,
                       'notebook_id': str(notebook_id),
                       'tags': '',
                       'data_sources': suggested_sources}
        return render(request, 'main/add_notebook.html', context=context)


@login_required(login_url="/")
def edit_notebook(request, notebook_id):
    oh_member = request.user.oh_member
    notebook = SharedNotebook.objects.get(pk=notebook_id)
    if notebook.oh_member != oh_member:
        messages.warning(request, 'Permission denied!')
        return redirect("/")
    if request.method == "POST":
        notebook.description = request.POST.get('description')
        tags = request.POST.get('tags')
        tags = [tag.strip() for tag in tags.split(',')]
        notebook.tags = json.dumps(tags)
        data_sources = request.POST.get('data_sources')
        data_sources = [ds.strip() for ds in data_sources.split(',')]
        notebook.data_sources = json.dumps(data_sources)
        notebook.updated_at = arrow.now().format()
        notebook.save()
        messages.info(request, 'Updated {}!'.format(notebook.notebook_name))
        return redirect("/dashboard")
    else:
        context = {'description': notebook.description,
                   'tags': notebook.get_tags(),
                   'data_sources': notebook.get_data_sources(),
                   'name': notebook.notebook_name,
                   'notebook_id': str(notebook_id)}
        return render(request, 'main/edit_notebook.html', context=context)


@login_required(login_url="/")
def delete_notebook(request, notebook_id):
    if request.method == "POST":
        oh_member = request.user.oh_member
        notebook = SharedNotebook.objects.get(pk=notebook_id)
        if notebook.oh_member != oh_member:
            messages.warning(request, 'Permission denied!')
            return redirect("/")
        notebook.delete()
        messages.info(request, 'Deleted {}!'.format(notebook.notebook_name))
        return redirect("/dashboard")


def notebook_index(request):
    order_variable = request.GET.get('order_by', 'updated_at')
    data_sources = get_all_data_sources()
    data_sources = sorted(data_sources)
    if order_variable not in ['updated_at', 'likes', 'views']:
        order_variable = 'updated_at'
    source_filter = request.GET.get('source', None)
    if source_filter:
        notebook_list = find_notebook_by_keywords(
                            source_filter,
                            search_field='data_sources')
    else:
        notebook_list = SharedNotebook.objects.filter(
            master_notebook=None)
    if order_variable == 'likes':
        notebook_list = notebook_list.annotate(
            likes=Count('notebooklike'))
    notebook_list = notebook_list.order_by('-{}'.format(order_variable))
    notebooks = paginate_items(notebook_list, request.GET.get('page'))
    return render(request,
                  'main/notebook_index.html',
                  {'notebooks': notebooks,
                   'section': 'explore',
                   'order_by': order_variable,
                   'data_sources': data_sources,
                   'source': source_filter})


def search_notebooks(request):
    if request.method == "POST":
        search_term = request.POST.get('search_term')
        notebook_list = find_notebook_by_keywords(search_term)
    else:
        search_term = request.GET.get('search_term', '')
        search_field = request.GET.get('search_field', None)
        notebook_list = find_notebook_by_keywords(search_term, search_field)
    order_variable = request.GET.get('order_by', 'updated_at')
    if order_variable not in ['updated_at', 'likes', 'views']:
        order_variable = 'updated_at'
    if order_variable == 'likes':
        notebook_list = notebook_list.annotate(

main/templates/main/about.html
{% extends 'main/base.html' %}
{% load static %}
{% block content %}

  <div class="container">
    <div class="row">
      <div class="col-md-5">
        <h2>About</h2>
        <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title">Who's running the <i>Exploratory</i>?</h3>
          </div>
          <div class="panel-body">
          <p>
            This project is run by
            <a href="https://openhumansfoundation.org/">the Open Humans Foundation</a>.
            You can always get in touch with it via email at <a href="mailto:support@openhumans.org">email</a> at <code>support@openhumans.org</code>.

            <a href='https://www.openhumans.org/activity/junos-personal-data-exploratory/'>See this project's activity page on Open Humans</a>.
          </p>
          </div>
        </div>
        <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title">Which data do you store?</h3>
          </div>
          <div class="panel-body">
          <p>
            We store different kinds of data depending on whether you are accessing this app as a guest
            or if you are being logged in with your Open Humans account:
          </p>
          <ol>
            <li>Generally, our hoster <i><a href='https://www.heroku.com'>Heroku</a></i> stores and gives us access to</li>
            <ol>
              <li>IP addresses used to access this app</li>
              <li>the sub-pages visited on this app</li>
              <li>(Both are stored for up to a week)</li>
            </ol>
            <li>By logging in with your <i>Open Humans</i> account we can access:</li>
            <ol>
              <li>your <i>Open Humans</i> username</li>
              <li>notebooks you've shared with Open Humans via the
                <a href="https://www.openhumans.org/activity/personal-data-notebooks/">Personal Data Notebooks</a> project.
              </li>
              <li>(You can always review this app's permissions <a href='https://www.openhumans.org/activity/junos-personal-data-exploratory/'>on Open Humans</a>)</li>
            </ol>
            <li>The Exploratory will store:</li>
            <ol>
              <li>your Open Humans username</li>
              <li>the authentication credentials that allow us to look at notebooks you have stored in the <a href="https://www.openhumans.org/activity/personal-data-notebooks/">Personal Data Notebooks</a> project</li>
              <li>notebooks that you have selected to publicly share through this app, along the description/tags/sources you enter</li>
              <li>if you like/comment on notebooks we store this data as well</li>
            </ol>
          </ol>
          <p>
            While you have to log-in through your Open Humans account to share your own notebooks, you can always use this site
            without registering to just open notebooks.
          </p>
          <p>
            The Exploratory is covered by Open Humans' <a href='https://www.openhumans.org/terms/'>Terms of Use</a> and
            <a href='https://www.openhumans.org/data-use/'>Data Use Policy</a>:
          </p>
          <p>
            You can always delete your account and all associated data from the <a href="{%url 'dashboard'%}"><i>Dashboard</i></a>.
            This includes the Open Humans authentication credentials, i.e. we won't be able to access your Open Humans account any longer.
          </p>
          <p>
            Removing the authorization on Open Humans does not automatically delete all your data in the Exploratory; if you
            want this to occur, you should delete your account here before withdrawing from this project in the Open Humans site.
          </p>
          </div>
        </div>
      </div>
      <div class="col-md-7">
        <h2>FAQ</h2>
        <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title">How do I share a notebook?</h3>
          </div>
          <div class="panel-body">
            <p>
              Sharing a notebook is a two-step process starting from
              <a href='https://notebooks.openhumans.org'><code>notebooks.openhumans.org</code></a> that involves first uploading
              it to Open Humans and then sharing it here:
            </p>
            <ol>
            <li>You can upload a notebook to Open Humans right from open notebooks on
            <code>notebooks.openhumans.org</code> by</li>
            <ol>
              <li>clicking on the <code>File</code> menu,</li>
              <li>selecting <code>Share Notebook</code>,</li>
              <li>and clicking <code>Upload to Open Humans</code></li>
            </ol>
            <li>Post-sharing you will be taken back to the <i>Exploratory</i>. After you have logged in you can share by:</li>
            <ol>
              <li>Selecting shareable notebooks from the <a href="{%url 'dashboard'%}">left side of your <i>dashboard</i></a>.</li>
              <li>Click <code>add/replace</code> to start the import of the notebook.
                (If you have previously shared a notebook of the same name the existing one will be updated)</li>
              <li>In the form that will appear you should give your notebook a <code>Description</code>,
                along with some <code>Tags</code> that describe your notebook. The <code>Data sources</code> your
              notebook requires should have been automatically identified. If not, you can manually add them.</li>
              <li>Press <code>Submit Notebook</code> and you are done. Your notebook is now shared on the
                <i><a href="{%url 'notebook-index'%}">list of notebooks</a></i>.</li>
            </ol>
          </ol>
          <p>Check out this quick GIF below to see how it works in practice:</p>
          <img data-gifffer="{% static 'aboutgifs/sharing.gif' %}" data-gifffer-width="100%" />
          </div>
        </div>
        <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title">How do I run one of the notebooks?</h3>
          </div>
          <div class="panel-body">
          <p>
            Getting a notebook copied into your own <code>notebooks.openhumans.org</code> structure is a simple click.
            When you see a notebook on the <i>Exploratory</i> that you'd like to run just press the <code>open as notebook</code> or <code>Open</code> buttons
            which are on <i><a href="{%url 'notebook-index'%}">list of notebooks</a></i>. If your notebook directory already contains a notebook of the same
            name it will make sure to append the current date/time to the newly imported notebook, as to not overwrite the existing one.
          </p>
          <p>
            See the GIF below for an example:
          </p>
          <img data-gifffer="{% static 'aboutgifs/index.gif' %}" data-gifffer-width="100%" />
          </div>
        </div>
        <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title">Can I edit/delete notebooks I've shared?</h3>
          </div>
          <div class="panel-body">
          <p>
            Yes, you can. Head to your <a href="{%url 'dashboard'%}"><i>Dashboard</i></a> (<code>My Notebooks</code> in the menu bar above).
            There you can <code>delete</code> a notebook or select <code>edit description</code> to change the tags/sources/description of a notebook you have published.
          </p>
          <p>
            Note that the <code>edit description</code> does not give a way to edit the notebook itself, but just the associated metadata. To also replace the code notebook itself
            you will have to replace it as outlined above in <i>How do I share a notebook?</i>
          </p>
          <img style='height: 100%; width: 100%; object-fit: contain' src="{% static 'aboutgifs/edit.png' %}"/>
          </div>
        </div>
        <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title">Can I use the exploratory for notebooks not hosted on <i>Open Humans</i>?</h3>
          </div>
          <div class="panel-body">
          <p>
            Unfortunately not at this point. But if you run your own JupyterHub installation you can easily set up your
            own exploratory for it. The required Jupyter extensions and the exploratory are all open source.
            <a href="https://github.com/gedankenstuecke/jupyter-gallery">Read more about it on the
            GitHub repository</a> for the exploratory!
          </p>
          </div>
        </div>
        <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title">Why isn't my notebook on the <i>Explore</i> page? / What are the <i>Other Notebooks</i> I see when looking at some notebooks?</h3>
          </div>
          <div class="panel-body">
          <p>
            We are grouping notebooks by their name.
            So if you are submitting a notebook called <code>mynotebook.ipynb</code>,
            but there is already another notebook of the same name we assume that your
            notebook is a (potentially edited) copy of this notebook.
            To keep things a bit more organized we are grouping these together and only list
            the oldest notebook with that name on the <i>Explore</i> page.
          </p>
          <p>
            If your notebook isn't an edited copy of an earlier notebook and you want to avoid
            being grouped with an existing notebook you should rename your notebook prior
            to publishing it.
          </p>
          </div>
        </div>
      </div>
  </div>
</div>

{% endblock %}

main/templates/main/notebook_details.html
{% extends 'main/base.html' %}
{% block content %}
{% load static %}
{% load utilities %}

<h1>
  Details for <code>{{notebook.notebook_name}}</code>
  <a href='{% url 'open-notebook' notebook.id %}?target=voila'><button type="button" class="btn btn-primary">Open <i class="fas fa-external-link-alt"></i></button></a>
  <a href='{% url 'open-notebook' notebook.id %}'><button type="button" class="btn btn-info">Edit & Run <i class="fas fa-pencil-alt"></i></button></a>
</h1>
<h4><small>
  Published by
  <a href="{%url 'search' %}?search_term={{notebook.oh_member.oh_username}}&search_field=username">
  <i>{{notebook.oh_member.oh_username}}</i>
  </a>
  {%if notebook.master_notebook%}
  (This notebook is an edited copy of
    <a href="{%url 'notebook-details' notebook.master_notebook.id%}">{{notebook.master_notebook.oh_member.oh_username}}'s notebook</a>)
  {%endif%}
</small></h4>
<div class="row">
  <div class="col-md-5">
    <p>
    <h4><i class="fas fa-book-open"></i> Description</h4>
    {{notebook.description|markdown}}
    </p>
    <h3>
      <button data-toggle="tooltip" data-container='body' data-placement="top" title='Number of views' class="btn btn-default btn-xs"><i class="fas fa-eye"></i> {{notebook.views}}</button>
      {%if request.user.is_authenticated %}
      <form action="{% url 'like-notebook' notebook.id %}" method="post">
        {% csrf_token %}
        <button type="submit" value="like_notebook" data-toggle="tooltip" data-container='body' data-placement="top" title='Number of Likes. Press to {%if liked%}un{%endif%}like.' class="btn btn-default btn-xs"><i class="fa{%if liked%}s{%else%}r{%endif%} fa-heart"></i> {{notebook.notebooklike_set.all|length}}</button>
      </form>
      {%else%}
      <a class="btn btn-default btn-xs" href="https://www.openhumans.org/direct-sharing/projects/oauth2/authorize/?client_id={{ client_id }}&response_type=code&redirect_uri={{ redirect_uri }}"
        data-toggle="tooltip" data-container='body' data-placement="top" title='Number of Likes. Please log in to like.'><i class="far fa-heart"></i> {{notebook.notebooklike_set.all|length}}</a>
      {%endif%}
    </h3>
    <p>
    <h4><i class="fas fa-tags"></i> Tags & Data Sources</h4>
    {%for tag in notebook.get_tags_json%}
    <a href="{%url 'search' %}?search_term={{tag}}&search_field=tags">
    <span class="label label-primary">{{tag}}</span>
    </a>
    {%endfor%}
    {%for source in notebook.get_data_sources_json%}
    <a href="{%url 'notebook-index'%}?source={{source}}">
    <span class="label label-info">{{source}}</span>
    </a>
    {%endfor%}
    </p>
    <p>
      <a href='{% url 'open-notebook' notebook.id %}?target=voila'><button type="button" class="btn btn-primary">Run Notebook <i class="fas fa-external-link-alt"></i></button></a>
      <a href='{% url 'open-notebook' notebook.id %}'><button type="button" class="btn btn-info">Edit & Run Notebook <i class="fas fa-pencil-alt"></i></button></a>
    </p>
    {% if notebook.master_notebook or other_notebooks%}
    <h4><i class="far fa-copy"></i> Other Notebook Versions</h4>
    <ul>
      {%if notebook.master_notebook%}<li><a href="{%url 'notebook-details' notebook.master_notebook.id%}">{{notebook.master_notebook.oh_member.oh_username}}'s notebook</a> (original notebook)</li>{%endif%}
      {%for other_notebook in other_notebooks%}
      <li><a href="{%url 'notebook-details' other_notebook.id%}">{{other_notebook.oh_member.oh_username}}'s notebook</a></li>
      {%endfor%}
    </ul>
    {%endif%}
    <h4><i class="far fa-comments"></i> Comments</h4>
    {%for comment in notebook.notebookcomment_set.all%}
    <blockquote>
      <p>{{comment.comment_text}}</p>
      <footer>
        <b>
          <a href="https://www.openhumans.org/member/{{comment.oh_member.oh_username}}/">{{comment.oh_member.oh_username}}</a>
        </b>, {{comment.created_at|timesince}} ago
      </footer>
    </blockquote>
        {%endfor%}
        {% if request.user.is_authenticated %}
        <form action="{% url 'add-comment' notebook.pk %}" method="post">
        {% csrf_token %}
        <div class="form-group">
          <label>Comment</label>
          <textarea class="form-control" rows=4 name="comment_text" size=50 type="text"
            placeholder="Enter your comment here" required></textarea>
            <p class="help-block">
            You have tried this notebook and have feedback?
            Or you have questions for the author? Give it a go!
            </p>
        </div>
        <input type="submit"
                value="Submit Comment"
                style="margin-top:6px;"
                class="btn btn-primary">
        </form>
      </br>
      {%else%}
      Please <a href="https://www.openhumans.org/direct-sharing/projects/oauth2/authorize/?client_id={{ client_id }}&response_type=code&redirect_uri={{ redirect_uri }}">
        log in to comment</a>.
        {%endif%}
  </div>
  <div class="col-md-7">
    <div>
      <ul class="nav nav-tabs" role="tablist">
        <li role="presentation" class="active"><a href="#output" aria-controls="output" role="tab" data-toggle="tab">Output</a></li>
        <li role="presentation"><a href="#code" aria-controls="code" role="tab" data-toggle="tab">Output & Code</a></li>
      </ul>
      <div class="tab-content">
        <div role="tabpanel" class="tab-pane active" id="output">
          <div class="panel panel-default">
            <div class="panel-heading">
              <h3 class="panel-title">Notebook <div style='float: right;'><small><i class="far fa-clock"></i> Last updated {{notebook.updated_at|timesince}} ago</small></style></h3>
            </div>
            <div class="panel-body">
              {{codeless_notebook_preview|safe}}
            </div>
          </div>
        </div>
      <div role="tabpanel" class="tab-pane" id="code">
        <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title">Notebook <div style='float: right;'><small><i class="far fa-clock"></i> Last updated {{notebook.updated_at|timesince}} ago</small></style></h3>
          </div>
          <div class="panel-body">
            {{notebook_preview|safe}}
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
</div>
{% endblock %}